# CR-053-UX-01: Read-and-Explore Tour seed for Menu Management course
# Step types per step:
#   highlight  = spotlight on visible element, auto-advance
#   explore    = user clicks safe UI action (open form/navigate); waits for click
#   for_real   = read-only description for save/delete/toggle moments; auto-advance
# Safety invariant: no "explore" step triggers a backend write.
import asyncio
import os
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv
from pathlib import Path

load_dotenv(Path(__file__).parent.parent / '.env')

MONGO_URL = os.environ['MONGO_URL']
DB_NAME = os.environ['DB_NAME']

COURSE = {
    "course_id": "menu-management",
    "title": "Menu Management",
    "description": "Learn to manage your menu confidently — categories, items, prices, variations, and bulk edits.",
    "icon": "menu",
    "cover_color": "#329937",
    "difficulty": "beginner",
    "estimated_time_minutes": 32,
    "status": "active",
    "mission_count": 13,
    "version": 2,
    "tour_mode": "read_and_explore",
    "display_order": 1,
}


MISSIONS = [
    # M1 ────────────────────────────────────────────────────────────────────
    {
        "mission_id": "menu-navigate",
        "course_id": "menu-management",
        "title": "Navigate to Menu Management",
        "description": "Find the Menu Management page and understand its layout.",
        "display_order": 1,
        "estimated_time_minutes": 1,
        "difficulty": "beginner",
        "is_optional": False,
        "steps": [
            {"step_id": "s1", "order": 1, "step_type": "explore",
             "instruction": "Click the Menu icon to open Menu Management.",
             "target": "[data-testid='sidebar-menu-management']",
             "action": "click",
             "validate": {"type": "url_contains", "value": "/menu"}},
            {"step_id": "s2", "order": 2, "step_type": "highlight",
             "instruction": "Welcome to Menu Management.",
             "detail": "The left side shows your categories. The right side shows the items in the selected category.",
             "target": "[data-testid='menu-management-panel']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='menu-management-panel']"},
             "auto_advance_seconds": 6},
            {"step_id": "s3", "order": 3, "step_type": "highlight",
             "instruction": "Categories group related items together.",
             "detail": "Starters, Main Course, Beverages, etc. The next mission will show you how to browse them.",
             "target": "[data-testid='category-list']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='category-list']"},
             "auto_advance_seconds": 5},
        ],
        "step_count": 3,
        "now_try_it": [
            "Open Menu Management once",
            "Count your existing categories",
        ],
    },

    # M2 ────────────────────────────────────────────────────────────────────
    {
        "mission_id": "menu-browse-categories",
        "course_id": "menu-management",
        "title": "Browse Categories",
        "description": "Navigate categories, search, and see items.",
        "display_order": 2,
        "estimated_time_minutes": 2,
        "difficulty": "beginner",
        "is_optional": False,
        "steps": [
            {"step_id": "s1", "order": 1, "step_type": "highlight",
             "instruction": "Find a category quickly with the search box.",
             "detail": "When you have many categories, type a name here to filter the list instantly.",
             "target": "[data-testid='category-search']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='category-search']"},
             "auto_advance_seconds": 5},
            {"step_id": "s2", "order": 2, "step_type": "explore",
             "instruction": "Click any category to see its items.",
             "detail": "Pick any one — the items in that category appear on the right.",
             "target": "[data-testid='category-list']",
             "action": "click",
             "validate": {"type": "click_target", "value": "[data-testid^='category-']"}},
            {"step_id": "s3", "order": 3, "step_type": "highlight",
             "instruction": "These are the items in the selected category.",
             "detail": "Each card shows the item name, price, and a colour-coded food type.",
             "target": "[data-testid='product-list']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='product-list']"},
             "auto_advance_seconds": 6},
            {"step_id": "s4", "order": 4, "step_type": "explore",
             "instruction": "Click 'All Items' to see everything at once.",
             "detail": "Useful when you're searching for a specific item across categories.",
             "target": "[data-testid='category-all']",
             "action": "click",
             "validate": {"type": "click_target", "value": "[data-testid='category-all']"}},
        ],
        "step_count": 4,
        "now_try_it": [
            "Browse 3 different categories",
            "Use the category search",
            "Try the 'All Items' view",
        ],
    },

    # M3 ────────────────────────────────────────────────────────────────────
    {
        "mission_id": "menu-view-items",
        "course_id": "menu-management",
        "title": "View Menu Items",
        "description": "Understand the item card and view switching.",
        "display_order": 3,
        "estimated_time_minutes": 2,
        "difficulty": "beginner",
        "is_optional": False,
        "steps": [
            {"step_id": "s1", "order": 1, "step_type": "highlight",
             "instruction": "Each card shows item name, price, and food type.",
             "detail": "The colour dot: green = vegetarian, red = non-vegetarian, yellow = egg.",
             "target": "[data-testid^='product-card-']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid^='product-card-']"},
             "auto_advance_seconds": 6},
            {"step_id": "s2", "order": 2, "step_type": "highlight",
             "instruction": "Switch between Normal view and Bulk Edit here.",
             "detail": "Normal = one item at a time. Bulk Edit = spreadsheet style for many items.",
             "target": "[data-testid='menu-type-selector']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='menu-type-selector']"},
             "auto_advance_seconds": 5},
            {"step_id": "s3", "order": 3, "step_type": "highlight",
             "instruction": "This is the Bulk Edit toggle.",
             "detail": "We'll explore the Bulk Editor in detail in Missions 11 and 11+. For now, just know it's here.",
             "target": "[data-testid='bulk-edit-toggle-btn']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='bulk-edit-toggle-btn']"},
             "auto_advance_seconds": 5},
        ],
        "step_count": 3,
        "now_try_it": [
            "Read 3 item cards",
            "Notice the colour dots and their meaning",
        ],
    },

    # M4 ────────────────────────────────────────────────────────────────────
    {
        "mission_id": "menu-add-item",
        "course_id": "menu-management",
        "title": "Add a New Menu Item",
        "description": "Learn the full Add Item flow — open the form, see every section, understand Save.",
        "display_order": 4,
        "estimated_time_minutes": 4,
        "difficulty": "beginner",
        "is_optional": False,
        "steps": [
            {"step_id": "s1", "order": 1, "step_type": "highlight",
             "instruction": "First, pick a category for your new item.",
             "detail": "Items belong to categories. Click the category your new item should land in.",
             "target": "[data-testid='category-list']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='category-list']"},
             "auto_advance_seconds": 5},
            {"step_id": "s2", "order": 2, "step_type": "explore",
             "instruction": "Click + Add Item to open the form.",
             "detail": "An empty form opens on the right. Nothing is saved until you click Save at the bottom.",
             "target": "[data-testid='add-product-btn']",
             "action": "click",
             "validate": {"type": "click_target", "value": "[data-testid='add-product-btn']"}},
            {"step_id": "s3", "order": 3, "step_type": "highlight",
             "instruction": "The form has clear sections, starting with Name & Sold By at the top.",
             "detail": "Look at the top: Name field (required) and Sold By (Kg / Litre / Piece). Description sits just below.",
             "target": "[data-testid='product-form']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='product-form']"},
             "auto_advance_seconds": 7},
            {"step_id": "s4", "order": 4, "step_type": "highlight",
             "instruction": "Pricing & Tax — set the selling price.",
             "detail": "Tax can be left at default if you're not sure. Edit anytime later.",
             "target": "[data-testid='section-pricing-&-tax']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='section-pricing-&-tax']"},
             "auto_advance_seconds": 6},
            {"step_id": "s5", "order": 5, "step_type": "highlight",
             "instruction": "Classification — mark Veg, Non-Veg, or Egg.",
             "detail": "The colour dot you saw on item cards comes from here.",
             "target": "[data-testid='section-classification']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='section-classification']"},
             "auto_advance_seconds": 6},
            {"step_id": "s6", "order": 6, "step_type": "for_real",
             "instruction": "This is the Save button — don't click during the tour.",
             "detail": "When you have a real item to add, click Save here. The form is empty right now, so a save would fail anyway.",
             "target": "[data-testid='product-form-save']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='product-form-save']"},
             "auto_advance_seconds": 7},
            {"step_id": "s7", "order": 7, "step_type": "highlight",
             "instruction": "Tour complete! Click the back arrow to close.",
             "detail": "Nothing was saved. The back arrow is at the top-left of the form, just before the form title.",
             "target": "[data-testid='product-form'] > div:first-child > button",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='product-form']"},
             "auto_advance_seconds": 6},
        ],
        "step_count": 7,
        "now_try_it": [
            "Pick one new item to add",
            "Choose its category first",
            "Open the form via + Add Item",
            "Fill in name + price + food type",
            "Save",
        ],
    },

    # M5 ────────────────────────────────────────────────────────────────────
    {
        "mission_id": "menu-edit-item",
        "course_id": "menu-management",
        "title": "Edit an Existing Item",
        "description": "Open and review an existing item's full edit form.",
        "display_order": 5,
        "estimated_time_minutes": 3,
        "difficulty": "beginner",
        "is_optional": False,
        "steps": [
            {"step_id": "s1", "order": 1, "step_type": "highlight",
             "instruction": "Every item card has small action icons in the corner.",
             "detail": "You'll see icons for full edit, quick edit, and delete.",
             "target": "[data-testid^='product-card-']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid^='product-card-']"},
             "auto_advance_seconds": 5},
            {"step_id": "s2", "order": 2, "step_type": "explore",
             "instruction": "Click the pencil icon on any item.",
             "detail": "This opens the full edit form for that item.",
             "target": "[data-testid^='full-edit-']",
             "action": "click",
             "validate": {"type": "click_target", "value": "[data-testid^='full-edit-']"}},
            {"step_id": "s3", "order": 3, "step_type": "highlight",
             "instruction": "The form opens with the item's current values pre-filled.",
             "detail": "The title at the top reads 'Edit: <item name>' so you always know which item you're editing.",
             "target": "[data-testid='product-form']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='product-form']"},
             "auto_advance_seconds": 6},
            {"step_id": "s4", "order": 4, "step_type": "highlight",
             "instruction": "All the same sections you saw in M4 are here.",
             "detail": "Name, Pricing, Classification, Channels, Variations, Addons. Change only what you need.",
             "target": "[data-testid='section-pricing-&-tax']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='section-pricing-&-tax']"},
             "auto_advance_seconds": 6},
            {"step_id": "s5", "order": 5, "step_type": "for_real",
             "instruction": "Save updates the existing item — don't click during the tour.",
             "detail": "When you really want to save your changes, click Save here.",
             "target": "[data-testid='product-form-save']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='product-form-save']"},
             "auto_advance_seconds": 6},
            {"step_id": "s6", "order": 6, "step_type": "highlight",
             "instruction": "Tour complete! Click the back arrow to close without saving.",
             "detail": "Top-left of the form.",
             "target": "[data-testid='product-form'] > div:first-child > button",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='product-form']"},
             "auto_advance_seconds": 6},
        ],
        "step_count": 6,
        "now_try_it": [
            "Open one item with the pencil icon",
            "Look at every section",
            "Close with the back arrow",
        ],
    },

    # M6 ────────────────────────────────────────────────────────────────────
    {
        "mission_id": "menu-quick-edit",
        "course_id": "menu-management",
        "title": "Quick Edit (Price & Name)",
        "description": "The fastest way to change just price or name.",
        "display_order": 6,
        "estimated_time_minutes": 2,
        "difficulty": "beginner",
        "is_optional": False,
        "steps": [
            {"step_id": "s1", "order": 1, "step_type": "highlight",
             "instruction": "Quick Edit is the fastest way to change just price or name.",
             "detail": "No full form, no extra clicks — useful for daily price tweaks.",
             "target": "[data-testid^='quick-edit-']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid^='quick-edit-']"},
             "auto_advance_seconds": 6},
            {"step_id": "s2", "order": 2, "step_type": "explore",
             "instruction": "Click the Quick Edit icon on any item.",
             "detail": "The card flips into edit mode with two compact fields.",
             "target": "[data-testid^='quick-edit-']",
             "action": "click",
             "validate": {"type": "click_target", "value": "[data-testid^='quick-edit-']"}},
            {"step_id": "s3", "order": 3, "step_type": "highlight",
             "instruction": "Two fields appear — Name and Price.",
             "detail": "Type your changes directly. Cancel discards anything you typed.",
             "target": "[data-testid='quick-edit-form']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='quick-edit-form']"},
             "auto_advance_seconds": 6},
            {"step_id": "s4", "order": 4, "step_type": "for_real",
             "instruction": "Save here applies the change immediately — don't click during the tour.",
             "detail": "When done viewing, click Cancel inside the card to close without changes.",
             "target": "[data-testid='quick-edit-save']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='quick-edit-save']"},
             "auto_advance_seconds": 6},
        ],
        "step_count": 4,
        "now_try_it": [
            "Quick-edit one item's price on your real menu",
            "Quick-edit one item's name",
        ],
    },

    # M7 ────────────────────────────────────────────────────────────────────
    {
        "mission_id": "menu-food-type",
        "course_id": "menu-management",
        "title": "Set Food Type (Veg / Non-Veg / Egg)",
        "description": "Make sure every item's food type is correct.",
        "display_order": 7,
        "estimated_time_minutes": 2,
        "difficulty": "beginner",
        "is_optional": False,
        "steps": [
            {"step_id": "s1", "order": 1, "step_type": "highlight",
             "instruction": "Every item has a food type dot — green, red, or yellow.",
             "detail": "Customers and staff rely on this colour to know what they're ordering.",
             "target": "[data-testid^='product-card-']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid^='product-card-']"},
             "auto_advance_seconds": 5},
            {"step_id": "s2", "order": 2, "step_type": "explore",
             "instruction": "Open the full edit form via the pencil icon.",
             "detail": "Food type lives in the Classification section of the full edit form.",
             "target": "[data-testid^='full-edit-']",
             "action": "click",
             "validate": {"type": "click_target", "value": "[data-testid^='full-edit-']"}},
            {"step_id": "s3", "order": 3, "step_type": "highlight",
             "instruction": "Find the Classification section.",
             "detail": "It contains the three food-type buttons.",
             "target": "[data-testid='section-classification']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='section-classification']"},
             "auto_advance_seconds": 6},
            {"step_id": "s4", "order": 4, "step_type": "highlight",
             "instruction": "Three buttons: Veg (green), Non-Veg (red), Egg (yellow).",
             "detail": "Whichever you pick shows on order screens, receipts, and reports.",
             "target": "[data-testid='section-classification']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='section-classification']"},
             "auto_advance_seconds": 6},
            {"step_id": "s5", "order": 5, "step_type": "for_real",
             "instruction": "Save updates the colour everywhere — don't click during the tour.",
             "detail": "Click the back arrow when you're done viewing.",
             "target": "[data-testid='product-form-save']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='product-form-save']"},
             "auto_advance_seconds": 6},
        ],
        "step_count": 5,
        "now_try_it": [
            "Spot-check 5 items on your menu — is the food type correct?",
            "Fix any that are wrong",
        ],
    },

    # M8 ────────────────────────────────────────────────────────────────────
    {
        "mission_id": "menu-toggle-availability",
        "course_id": "menu-management",
        "title": "Toggle Item Availability",
        "description": "Mark items in-stock or out-of-stock without deleting.",
        "display_order": 8,
        "estimated_time_minutes": 1,
        "difficulty": "beginner",
        "is_optional": False,
        "steps": [
            {"step_id": "s1", "order": 1, "step_type": "highlight",
             "instruction": "Every item card has a status toggle.",
             "detail": "ON = in stock, available to order. OFF = out of stock, hidden from order screen.",
             "target": "[data-testid^='status-toggle-']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid^='status-toggle-']"},
             "auto_advance_seconds": 6},
            {"step_id": "s2", "order": 2, "step_type": "for_real",
             "instruction": "Clicking the toggle marks the item in/out of stock — don't click now.",
             "detail": "When you're ready to mark something sold-out, click this toggle. We don't want to change live availability during the tour.",
             "target": "[data-testid^='status-toggle-']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid^='status-toggle-']"},
             "auto_advance_seconds": 7},
            {"step_id": "s3", "order": 3, "step_type": "highlight",
             "instruction": "Out-of-stock items appear greyed out.",
             "detail": "They stop showing on the customer-facing order screen. Toggle them back any time.",
             "target": "[data-testid='product-list']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='product-list']"},
             "auto_advance_seconds": 6},
        ],
        "step_count": 3,
        "now_try_it": [
            "Toggle one slow-moving item off",
            "Toggle it back on",
        ],
    },

    # M9 ────────────────────────────────────────────────────────────────────
    {
        "mission_id": "menu-delete-item",
        "course_id": "menu-management",
        "title": "Delete a Menu Item",
        "description": "Permanently remove an item — and when NOT to.",
        "display_order": 9,
        "estimated_time_minutes": 2,
        "difficulty": "beginner",
        "is_optional": False,
        "steps": [
            {"step_id": "s1", "order": 1, "step_type": "highlight",
             "instruction": "The trash icon permanently removes an item from your menu.",
             "detail": "Items deleted here are gone — but old orders for them are preserved in your reports.",
             "target": "[data-testid^='delete-']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid^='delete-']"},
             "auto_advance_seconds": 6},
            {"step_id": "s2", "order": 2, "step_type": "for_real",
             "instruction": "Don't click delete during the tour — let's just understand what happens.",
             "detail": "When you do click delete for real, a confirmation appears asking why.",
             "target": "[data-testid^='delete-']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid^='delete-']"},
             "auto_advance_seconds": 6},
            {"step_id": "s3", "order": 3, "step_type": "highlight",
             "instruction": "The confirmation asks for a deletion reason.",
             "detail": "Pick from: discontinued, replaced, mistake, etc. This helps you audit menu changes later.",
             "target": "[data-testid='product-list']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='product-list']"},
             "auto_advance_seconds": 6},
            {"step_id": "s4", "order": 4, "step_type": "highlight",
             "instruction": "Confirm makes the deletion permanent.",
             "detail": "The item is gone from your menu. Reports still show its past orders.",
             "target": "[data-testid='product-list']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='product-list']"},
             "auto_advance_seconds": 5},
            {"step_id": "s5", "order": 5, "step_type": "highlight",
             "instruction": "Delete only for items you'll never serve again.",
             "detail": "For temporary out-of-stock, use the toggle (Mission 8) instead.",
             "target": "[data-testid='product-list']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='product-list']"},
             "auto_advance_seconds": 6},
        ],
        "step_count": 5,
        "now_try_it": [
            "Identify 2 items you'd never delete (best sellers)",
            "Identify when delete vs toggle-off is the right choice",
        ],
    },

    # M10 ────────────────────────────────────────────────────────────────────
    {
        "mission_id": "menu-add-variation",
        "course_id": "menu-management",
        "title": "Add Item Variations",
        "description": "One item, multiple sizes or options with different prices.",
        "display_order": 10,
        "estimated_time_minutes": 4,
        "difficulty": "intermediate",
        "is_optional": False,
        "steps": [
            {"step_id": "s1", "order": 1, "step_type": "highlight",
             "instruction": "Variations let one item have multiple sizes or options.",
             "detail": "Like Small / Medium / Large pizzas, or Regular / Large coffee — each with its own price.",
             "target": "[data-testid^='product-card-']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid^='product-card-']"},
             "auto_advance_seconds": 6},
            {"step_id": "s2", "order": 2, "step_type": "explore",
             "instruction": "Open any item's edit form to see where variations live.",
             "detail": "Click the pencil icon on any item.",
             "target": "[data-testid^='full-edit-']",
             "action": "click",
             "validate": {"type": "click_target", "value": "[data-testid^='full-edit-']"}},
            {"step_id": "s3", "order": 3, "step_type": "highlight",
             "instruction": "Scroll down to the Food Variations section.",
             "detail": "This is where size or option choices go for this item.",
             "target": "[data-testid='section-food-variations']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='section-food-variations']"},
             "auto_advance_seconds": 6},
            {"step_id": "s4", "order": 4, "step_type": "highlight",
             "instruction": "Each variation gets its own name and price.",
             "detail": "Inside the Food Variations section, click + Add Variation to add a new one. Repeat for as many as you need.",
             "target": "[data-testid='section-food-variations']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='section-food-variations']"},
             "auto_advance_seconds": 7},
            {"step_id": "s5", "order": 5, "step_type": "for_real",
             "instruction": "Save stores the variations on this item — don't click during the tour.",
             "detail": "On the order screen, staff or customer picks which variation when ordering.",
             "target": "[data-testid='product-form-save']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='product-form-save']"},
             "auto_advance_seconds": 7},
            {"step_id": "s6", "order": 6, "step_type": "highlight",
             "instruction": "When you're done, click the back arrow to close without saving.",
             "detail": "Use variations for: pizzas (small/medium/large), coffee (regular/large), pasta (half/full), juice sizes.",
             "target": "[data-testid='product-form'] > div:first-child > button",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='product-form']"},
             "auto_advance_seconds": 6},
        ],
        "step_count": 6,
        "now_try_it": [
            "Pick one item that should have sizes",
            "Open it and add 2 variations",
            "Save and see how it shows on the order screen",
        ],
    },

    # M11 ────────────────────────────────────────────────────────────────────
    {
        "mission_id": "menu-bulk-editor",
        "course_id": "menu-management",
        "title": "Bulk Edit Intro",
        "description": "Spreadsheet-style editing for many items at once.",
        "display_order": 11,
        "estimated_time_minutes": 3,
        "difficulty": "intermediate",
        "is_optional": False,
        "steps": [
            {"step_id": "s1", "order": 1, "step_type": "explore",
             "instruction": "Click Bulk Edit to switch the items view into a spreadsheet.",
             "detail": "Rows = items, columns = name, price, type, GST, etc.",
             "target": "[data-testid='bulk-edit-toggle-btn']",
             "action": "click",
             "validate": {"type": "click_target", "value": "[data-testid='bulk-edit-toggle-btn']"}},
            {"step_id": "s2", "order": 2, "step_type": "highlight",
             "instruction": "Your menu is now a spreadsheet.",
             "detail": "Click any cell to edit it inline — name, price, GST, food type, anything.",
             "target": "[data-testid='product-list']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='product-list']"},
             "auto_advance_seconds": 7},
            {"step_id": "s3", "order": 3, "step_type": "highlight",
             "instruction": "Filter by category to focus on one section.",
             "detail": "Editing 200 items at once is overwhelming — filter to a category and edit that subset cleanly.",
             "target": "[data-testid='category-list']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='category-list']"},
             "auto_advance_seconds": 6},
            {"step_id": "s4", "order": 4, "step_type": "for_real",
             "instruction": "Bulk Edit holds changes until you click Save All — don't save during the tour.",
             "detail": "When done exploring, click Bulk Edit again (or the Normal toggle) to return.",
             "target": "[data-testid='bulk-edit-toggle-btn']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='bulk-edit-toggle-btn']"},
             "auto_advance_seconds": 7},
        ],
        "step_count": 4,
        "now_try_it": [
            "Open Bulk Edit",
            "Filter to one category",
            "Notice every editable field",
            "Switch back to Normal view",
        ],
    },

    # M11+ ────────────────────────────────────────────────────────────────────
    {
        "mission_id": "menu-bulk-editor-deep",
        "course_id": "menu-management",
        "title": "Bulk Editor Deep Dive",
        "description": "Excel import/export and best practices. Optional — for power users.",
        "display_order": 12,
        "estimated_time_minutes": 4,
        "difficulty": "advanced",
        "is_optional": True,
        "steps": [
            {"step_id": "s1", "order": 1, "step_type": "explore",
             "instruction": "Open Bulk Edit again so we can look at the import/export tools.",
             "detail": "Click the Bulk Edit toggle if you closed it earlier.",
             "target": "[data-testid='bulk-edit-toggle-btn']",
             "action": "click",
             "validate": {"type": "click_target", "value": "[data-testid='bulk-edit-toggle-btn']"}},
            {"step_id": "s2", "order": 2, "step_type": "highlight",
             "instruction": "Export your menu to Excel for offline editing.",
             "detail": "Useful for big price overhauls — open in Excel, edit comfortably, then re-import.",
             "target": "[data-testid='menu-management-panel']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='menu-management-panel']"},
             "auto_advance_seconds": 6},
            {"step_id": "s3", "order": 3, "step_type": "highlight",
             "instruction": "Re-import the edited Excel file.",
             "detail": "The system matches items by ID and updates only what changed. Renaming a column or row order doesn't matter — IDs are what counts.",
             "target": "[data-testid='menu-management-panel']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='menu-management-panel']"},
             "auto_advance_seconds": 7},
            {"step_id": "s4", "order": 4, "step_type": "for_real",
             "instruction": "Use Bulk Edit for: annual price updates, GST changes, bulk renaming.",
             "detail": "Always click Save All before leaving the page — unsaved changes are discarded.",
             "target": "[data-testid='menu-management-panel']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='menu-management-panel']"},
             "auto_advance_seconds": 7},
        ],
        "step_count": 4,
        "now_try_it": [
            "Export your menu to Excel",
            "Edit 2 prices in Excel",
            "Re-import and confirm changes saved",
        ],
    },

    # M12 ────────────────────────────────────────────────────────────────────
    {
        "mission_id": "menu-add-category",
        "course_id": "menu-management",
        "title": "Create a New Category",
        "description": "Add a new menu category and assign its kitchen station.",
        "display_order": 13,
        "estimated_time_minutes": 2,
        "difficulty": "beginner",
        "is_optional": False,
        "steps": [
            {"step_id": "s1", "order": 1, "step_type": "highlight",
             "instruction": "Look for + Add Category at the bottom of the category list.",
             "detail": "It's a dashed orange button under your existing categories.",
             "target": "[data-testid='add-category-btn']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='add-category-btn']"},
             "auto_advance_seconds": 5},
            {"step_id": "s2", "order": 2, "step_type": "explore",
             "instruction": "Click + Add Category to open the inline form.",
             "detail": "An inline form expands below the categories — no full-screen modal.",
             "target": "[data-testid='add-category-btn']",
             "action": "click",
             "validate": {"type": "click_target", "value": "[data-testid='add-category-btn']"}},
            {"step_id": "s3", "order": 3, "step_type": "highlight",
             "instruction": "Give the category a clear name.",
             "detail": "Examples: 'Lunch Specials', 'Bar Menu', 'Kids Menu'.",
             "target": "[data-testid='new-category-input']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='new-category-input']"},
             "auto_advance_seconds": 6},
            {"step_id": "s4", "order": 4, "step_type": "highlight",
             "instruction": "Pick which kitchen station prepares items in this category.",
             "detail": "Hot Kitchen, Cold Kitchen, Bar — whichever KDS screen this category routes to.",
             "target": "[data-testid='new-category-station']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='new-category-station']"},
             "auto_advance_seconds": 6},
            {"step_id": "s5", "order": 5, "step_type": "for_real",
             "instruction": "The green Add button creates the category — don't click during the tour.",
             "detail": "Click Cancel (the grey button) to close the inline form without saving.",
             "target": "[data-testid='new-category-station']",
             "action": "observe",
             "validate": {"type": "element_visible", "value": "[data-testid='new-category-station']"},
             "auto_advance_seconds": 7},
        ],
        "step_count": 5,
        "now_try_it": [
            "Plan a new category your restaurant could use",
            "Open the Add Category form",
            "See the kitchen station options",
            "Either save the new category or close without saving",
        ],
    },
]


async def main():
    client = AsyncIOMotorClient(MONGO_URL)
    db = client[DB_NAME]

    # Upsert course
    await db.training_courses.replace_one(
        {"course_id": COURSE["course_id"]}, COURSE, upsert=True
    )
    print(f"Course seeded: {COURSE['course_id']} ({len(MISSIONS)} missions)")

    # Upsert missions (full replace — versioning lives on the doc)
    total_steps = 0
    for mission in MISSIONS:
        mission_doc = {**mission, "version": 2, "status": "active"}
        await db.training_missions.replace_one(
            {"mission_id": mission["mission_id"]}, mission_doc, upsert=True
        )
        total_steps += mission["step_count"]
        print(f"  Mission seeded: {mission['mission_id']} ({mission['step_count']} steps)")

    print(f"\nDone: 1 course, {len(MISSIONS)} missions, {total_steps} steps")
    client.close()


if __name__ == "__main__":
    asyncio.run(main())
